In [4]:
# 1. Import the NUMPY package under the name np.
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [5]:
# 2. Print the NUMPY version and the configuration.
print(np.__version__)
np.show_config()

2.0.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
     

/Users/finko/Library/Python/3.9/lib/python/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [13]:
print(a)

[[[0.05491722 0.17843094 0.42929272 0.26908685 0.62044844]
  [0.08362673 0.32298509 0.4279934  0.71600922 0.33539035]
  [0.20189263 0.48585012 0.78417035 0.4253628  0.66592751]]

 [[0.55474455 0.47950957 0.94370483 0.28156291 0.67016079]
  [0.68070711 0.58312651 0.57558126 0.46983719 0.07367905]
  [0.44315003 0.57458764 0.7990518  0.8102651  0.45989524]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [15]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
# No, because they have different shapes: (2,3,5) and (5,2,3)
try:
    a + b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [18]:
c = b.transpose(1, 2, 0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
d = a + c
# It works because now both arrays have the same shape: (2,3,5)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [20]:
print("a:\n", a)
print("d:\n", d)
# d is just a with 1 added to every element

a:
 [[[0.05491722 0.17843094 0.42929272 0.26908685 0.62044844]
  [0.08362673 0.32298509 0.4279934  0.71600922 0.33539035]
  [0.20189263 0.48585012 0.78417035 0.4253628  0.66592751]]

 [[0.55474455 0.47950957 0.94370483 0.28156291 0.67016079]
  [0.68070711 0.58312651 0.57558126 0.46983719 0.07367905]
  [0.44315003 0.57458764 0.7990518  0.8102651  0.45989524]]]
d:
 [[[1.05491722 1.17843094 1.42929272 1.26908685 1.62044844]
  [1.08362673 1.32298509 1.4279934  1.71600922 1.33539035]
  [1.20189263 1.48585012 1.78417035 1.4253628  1.66592751]]

 [[1.55474455 1.47950957 1.94370483 1.28156291 1.67016079]
  [1.68070711 1.58312651 1.57558126 1.46983719 1.07367905]
  [1.44315003 1.57458764 1.7990518  1.8102651  1.45989524]]]



### 12. Multiply a and c. Assign the result to e.


In [21]:
e = a * c



### 13. Does e equal to a? Why or why not?


In [22]:
print(np.array_equal(e, a))
# Yes, because multiplying by 1 does not change the values

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [25]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [24]:
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [26]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [27]:
print("d:\n", d)
print("f:\n", f)

d:
 [[[1.05491722 1.17843094 1.42929272 1.26908685 1.62044844]
  [1.08362673 1.32298509 1.4279934  1.71600922 1.33539035]
  [1.20189263 1.48585012 1.78417035 1.4253628  1.66592751]]

 [[1.55474455 1.47950957 1.94370483 1.28156291 1.67016079]
  [1.68070711 1.58312651 1.57558126 1.46983719 1.07367905]
  [1.44315003 1.57458764 1.7990518  1.8102651  1.45989524]]]
f:
 [[[  0.  25.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  25. 100.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [28]:
f_string = np.empty(d.shape, dtype=str)
f_string[(d > d_min) & (d < d_mean)] = "B"
f_string[(d > d_mean) & (d < d_max)] = "D"
f_string[d == d_mean] = "C"
f_string[d == d_min] = "A"
f_string[d == d_max] = "E"
print("f_string:\n", f_string)

f_string:
 [[['A' 'B' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'D']]

 [['D' 'B' 'E' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'B']]]
